AllideaBridge/gymming_app

lib/drawer/trainer_drawer.dart, lib/trainee_registration/trainee_registration.dart, lib/trainer_timetable/trainer_timetable.dart
[Screen_recording_20240218_223837.webm](https://github.com/AllideaBridge/gymming_app/assets/55073966/9cc950d7-be71-45e7-922d-fb4818e48bea)
=> [Register] 새 회원 등록 목업 만들기

lib/common/component/request.dart, lib/drawer/trainer_drawer.dart, lib/models/trainee_list.dart, lib/repositories/trainee_repository.dart, lib/user_management/user_management_list.dart
=> [Feature] 회원관리 목록 구현

lib/common/component/common_header.dart, lib/common/constants.dart, lib/trainee_registration/trainee_registration.dart
- 키패드 올라와서 입력 중인 경우 화면 클릭 시 다시 키패드가 내려가도록 변경 
- 아직 각 input 별 validation은 없는 상태
- 전체 validation 및 최종 등록 버튼의 변경상태도 아직 없음 
[Screen_recording_20240228_201236.webm](https://github.com/AllideaBridge/gymming_app/assets/55073966/99cb3a47-e964-4627-9ced-248a96259f6d)
=> 트레이너의 회원 등록 화면 구현

lib/components/common_header.dart, lib/pages/gymbie/gymbie_home/component/gymbie_schedule_modal.dart, lib/pages/gymbie/gymbie_schedule_change/component/gymbie_change_calendar.dart, lib/pages/gymbie/gymbie_schedule_change/component/gymbie_select_time.dart, lib/pages/gymbie/gymbie_schedule_change/gymbie_schedule_change.dart, lib/services/models/available_times.dart, lib/services/repositories/schedule_repository.dart
=> [Feature] Gymbie 일정 변경 화면 API 연결

lib/pages/gymbie/gymbie_home/component/gymbie_home_calendar.dart, lib/pages/gymbie/gymbie_home/component/gymbie_schedule_modal.dart, lib/pages/gymbie/gymbie_schedule_cancel.dart, lib/services/models/schedule_info.dart, lib/services/repositories/schedule_repository.dart
- 첫 화면 달력조회 api 변경에 따른 수정
- 스케쥴 취소 api 추가
=> [Gymbie Schedule Cancel] 회원의 스케쥴 취소 api 추가

lib/pages/gymbie/gymbie_schedule_change/gymbie_schedule_change.dart, lib/services/models/available_times.dart, lib/services/models/schedule_info.dart, lib/services/repositories/schedule_repository.dart
- 일정 변경 API에 에러가 있어 제대로 동작하지는 않는 상황입니다.
- 일정 변경 버튼 클릭 시 일정 변경 API를 보내도록 했습니다.
- 사유를 입력해야 하는 경우에는 기획 의도를 한번 더 확인한 후 작업할 예정입니다.
=> [Feature] Gymbie 일정 변경 API 연결

lib/components/layouts/reason_layout.dart, lib/pages/gymbie/gymbie_schedule_cancel.dart, lib/pages/gymbie/gymbie_schedule_change/gymbie_schedule_change.dart, lib/pages/gympro/gympro_requests/gympro_finished_request_list.dart, lib/pages/gympro/gympro_requests/gympro_pending_request_list.dart, lib/services/repositories/request_repository.dart, lib/services/repositories/schedule_repository.dart, lib/services/utils/date_util.dart
- Gymbie가 Gympro에게 일정을 변경하고 취소하는 요청을 보내는 API를 연결했습니다.
=> [Feature] Gymbie 일정 변경/취소 요쳥 API 연결

lib/pages/gymbie/drawer/gymbie_drawer.dart, lib/pages/gympro/gympro_requests/gympro_finished_request_list.dart, lib/pages/gympro/gympro_requests/gympro_pending_request_list.dart, lib/services/models/request_list.dart, lib/services/repositories/request_repository.dart, lib/services/utils/date_util.dart
- 아직 프로필 이미지가 응답값에 포함되어 있지 않아 하드코딩 해두었습니다.
=> 트레이너 요청 목록 API 연결

lib/components/input_filed.dart, lib/pages/gymbie/drawer/gymbie_drawer.dart, lib/pages/gymbie/gymbie_home/gymbie_home.dart, lib/pages/sample/sample_page.dart
```dart
final TextEditingController controller = TextEditingController();
InputField(
controller: controller,
title: 'title',
// optional: 입력된 값이 Default
placeHolder = '입력하세요',
// 필수값 표시 여부
isRequired = false,
// 클릭했을 때 나타날 키보드의 타입 - TextInputType 형식으로 넘겨주어야 함.
// TextInputType.text / TextInputType.number / TextInputType.emailAddress
type = TextInputType.text,
)
```
=> 기본 입력 필드 컴포넌트 구현

lib/components/text_dropdown.dart
##Changes
- ReasonLayout 에서 만들어져 있는 코드를 이용
- 현재 setter 메소드에 setState 메소드를 넣으면 결과를 가져옴
=> 드롭다운 컴포넌트 추가 

lib/components/profile_image.dart, pubspec.yaml
```dart
ProfileImage(
size: 130.0,
// originUrl 형식은 추후 변경 예정
originImgUrl: null,
)
```
=> [Feature] 프로필 이미지 컴포넌트 구현

lib/components/modals/basic_modal.dart
=> 베이직 모달 생성, 추가 메소드 구현 하지 않음

lib/components/input_filed.dart
```dart
bool _isValid = false;
void handleValidationChanged(bool isValid) {
setState(() {
_isValid = isValid;
});
}
...
InputField(
controller: _controller,
title: '이름',
validator: (val) {
if (val.length < 1) return '이름은 필수값입니다.';
},
onValidationChanged: handleValidationChanged,
),
```
=> [Feature] InputField 컴포넌트 Validation 추가

lib/components/birthday_select.dart, lib/components/phone_number_select.dart, lib/components/text_dropdown.dart
생년월일, 전화번호 벨리데이현 화면 구현하였습니다.
실제 값 벨리데이션은 해당 값을 setter 로 받는 쪽에서 별개 처리해야 합니다. (null 체크 및 개수 체크 등)
=> 드롭다운, 생년월일, 전화번호 벨리데이션 구현 

lib/components/available_time.dart, lib/components/buttons/primary_button.dart, lib/components/input_filed.dart, lib/components/layouts/gympro_infos/gympro_info_step1.dart, lib/components/layouts/gympro_infos/gympro_info_step2.dart, lib/components/layouts/gympro_infos/gympro_info_step3.dart, lib/pages/gympro/drawer/gympro_drawer.dart, lib/pages/gympro/gympro_register.dart, lib/pages/sample/sample_page.dart
=> 트레이너 회원가입 화면 구현 - 1st

lib/components/available_time.dart, lib/components/buttons/primary_button.dart, lib/components/layouts/gympro_infos/gympro_info_step2.dart, lib/pages/gympro/gympro_register.dart, lib/pages/sample/sample_page.dart
=> [Feature] Step2 Validation 구현

lib/components/phone_number_select.dart, lib/pages/gymbie/gymbie_register.dart, lib/pages/sample/sample_page.dart
- 전화번호 벨리데이션 오류 수정
- 회원 회원가입 이름 수정
=> 회원 회원가입 화면 오류 수정 

lib/components/layouts/gympro_infos/gympro_info_step3.dart, lib/components/profile_card.dart, lib/pages/gymbie/gymbie_register.dart, lib/pages/gympro/gympro_register.dart, lib/pages/login/signin_success.dart
- 트레이너 회원가입 화면 개발 완료
- API 연동은 추후 개발 예정
=> 트레이너 회원가입 화면 개발 (API 연동 外)

lib/common/constants.dart, lib/components/layouts/gympro_infos/gympro_info_step1.dart, lib/components/layouts/gympro_infos/gympro_info_step3.dart, lib/components/phone_number_select.dart, lib/pages/gymbie/gymbie_register.dart, lib/services/utils/validate_util.dart
=> 회원가입 시 전화번호 형식 변경 및 검증로직 추가 

lib/components/modals/basic_modal.dart, lib/pages/gympro/gympro_register.dart, lib/pages/login/signin_success.dart
=> [Feature] 회원가입 완료 Modal

lib/components/schedule_select_calendar.dart, lib/pages/gymbie/gymbie_home/component/gymbie_schedule_item.dart, lib/pages/gymbie/gymbie_home/component/gymbie_schedule_list.dart, lib/pages/gymbie/gymbie_home/component/gymbie_schedule_modal.dart, lib/pages/gymbie/gymbie_home/gymbie_home.dart, lib/pages/gymbie/gymbie_schedule_change.dart, lib/pages/gymbie/gymbie_schedule_create.dart, lib/pages/gymbie/gymbie_schedule_trainer_list.dart, lib/pages/gympro/gympro_home/gympro_disable_time.dart, lib/services/models/schedule_user.dart, lib/services/models/trainer_list.dart, lib/services/repositories/schedule_repository.dart, lib/services/utils/date_util.dart
아직 구현되지 않은 것
- 시간 기준으로 선택/선택불가능 (두개씩 선택?) 기능
리팩토링 필요
- 스케쥴 생성/스케쥴 변경 화면이 같은 메소드를 여럿 공유
=> 회원의 스케쥴 생성 화면 만들기

lib/components/time_select_table.dart, lib/pages/gymbie/gymbie_home/component/gymbie_schedule_modal.dart
- 선택된 스케줄이 지금보다 과거인 경우에 상세 모달 띄우면 수정/취소 버튼을 안보이게 변경
- 스케줄 생성/수정 시 스케줄 시간(칩) 선택할 때 연속된 두 개로 선택이 되도록 하고, 그렇게 선택 못하는 시간이면 아예 선택 안되게 처리
=> Schedule pick available time

lib/pages/gymbie/drawer/gymbie_drawer.dart, lib/pages/gymbie/explore/component/profile_img.dart, lib/pages/gymbie/explore/explore_detail.dart, lib/pages/gymbie/gymbie_register.dart, lib/pages/gympro/drawer/gympro_drawer.dart, lib/pages/gympro/gympro_register.dart, lib/services/repositories/trainer_repository.dart
- 아직 회원정보를 가져오는 로직이 불완전해서 추가 테스트 필요
=> 회원/트레이너 정보 수정 화면 연결

lib/components/birthday_select.dart, lib/components/schedule_select_calendar.dart, lib/components/time_select_table.dart, lib/main.dart, lib/pages/gymbie/gymbie_home/component/gymbie_home_calendar.dart, lib/pages/gymbie/gymbie_home/component/gymbie_schedule_modal.dart, lib/pages/gymbie/gymbie_schedule_cancel.dart, lib/pages/gymbie/gymbie_schedule_change.dart, lib/pages/gymbie/gymbie_schedule_create.dart, lib/pages/gympro/gympro_home/gympro_disable_time.dart, lib/pages/gympro/gympro_member_mgmt/component/gympro_member_detail_calendar.dart, lib/services/utils/date_util.dart, pubspec.yaml
- timezone 패키지 추가 
- DateTime.now() 를 한국 시간 기준으로 변경
=> DAteTime.now 를 한국 시간으로 변경

lib/components/layouts/reason_layout.dart, lib/pages/gymbie/gymbie_change_ticket/gymbie_change_ticket_detail.dart, lib/pages/gymbie/gymbie_change_ticket/gymbie_change_ticket_list.dart, lib/pages/gymbie/gymbie_home/component/gymbie_schedule_modal.dart, lib/pages/gymbie/gymbie_schedule_resolve_ticket.dart, lib/pages/gympro/gympro_change_ticket/gympro_change_ticket_list.dart, lib/pages/gympro/gympro_change_ticket/gympro_request_detail.dart, lib/pages/gympro/gympro_register.dart, lib/services/repositories/change_ticket_repository.dart
- ChangeTicketRepository에 ApiService 상속하면서 불필요한 http client 코드 제거
- 버튼이 2개가 밑에 있는 경우 발생한 에러 수정
- 버튼 2개를 row에 넣을 때 각각 버튼을 Expanded 로 감싸주어야 함
=> change ticket repository 수정 및 버튼 변경에 따른 에러 수정 

lib/components/layouts/gympro_infos/gympro_info_step2.dart, lib/pages/gympro/gympro_register.dart, lib/pages/login/signin_success.dart
=> 트레이너 회원가입 중 자동 승인 기간 관련 안내 테이블 추가

lib/pages/gympro/gympro_member_connect/gympro_member_connect.dart, lib/pages/gympro/gympro_member_mgmt/gympro_member_detail.dart, lib/pages/gympro/gympro_member_mgmt/gympro_member_extend.dart, lib/services/models/trainer_user.dart, lib/services/repositories/trainer_user_repository.dart
=> [Feature] 연장 등록 화면 추가

lib/pages/gymbie/gymbie_register.dart, lib/pages/gympro/gympro_gymbie_remove.dart, lib/pages/gympro/gympro_member_connect/gympro_member_connect.dart, lib/pages/gympro/gympro_member_connect/gympro_member_search.dart, lib/pages/gympro/gympro_member_mgmt/gympro_member_detail.dart, lib/pages/gympro/gympro_member_mgmt/gympro_member_extend.dart, lib/pages/gympro/gympro_member_mgmt/gympro_member_mgmt.dart, lib/services/models/trainer_user.dart, lib/services/models/trainer_user_detail.dart, lib/services/models/user_detail.dart, lib/services/repositories/trainer_user_repository.dart, lib/services/repositories/user_repository.dart
=> 트레이너의 회원 연결/상세/삭제 화면의 API 연결 및 수정 
